from huggingface_hub import InferenceClient
import re
import os
import json

# Initialize Hugging Face client with your token (set HF_TOKEN in environment)
client = InferenceClient(
    "meta-llama/Llama-3-70b-instruct",
    token=os.getenv("HF_TOKEN")  # safer: set as environment variable
)

USE_REMOTE = True
token_usage = {"input": 0, "output": 0, "total": 0}  # usage counter

def plan_workflow(user_input: str) -> str:
    if USE_REMOTE:
        try:
            prompt = f"""
            You are an expert orchestrator.
            Convert the following request into a structured workflow plan.
            Request: {user_input}
            Available APIs: flight_api, hotel_api, weather_api, activity_api, stock_api
            Output ONLY valid JSON with correct parameters from the request.
            """

            # Count input tokens (approx: 1 token ≈ 4 chars)
            token_usage["input"] += len(prompt) // 4

            response = client.text_generation(
                prompt,
                max_new_tokens=300,
                temperature=0.2
            )

            # Count output tokens (approx: 1 token ≈ 4 chars)
            token_usage["output"] += len(response) // 4
            token_usage["total"] = token_usage["input"] + token_usage["output"]

            print("[INFO] Workflow generated by LLaMA 3 70B")
            print(f"[USAGE] Input: {token_usage['input']} | Output: {token_usage['output']} | Total: {token_usage['total']} tokens")
            return response

        except Exception as e:
            print(f"[WARN] Remote LLaMA API failed: {e}")
            return local_fallback(user_input)
    else:
        print("[INFO] Workflow generated by local fallback")
        return local_fallback(user_input)


def local_fallback(user_input: str) -> str:
    """
    Simple regex-based fallback parser.
    Extracts origin, destination, and activity keywords from user input.
    """
    origin_match = re.search(r"from\s+(\w+)", user_input, re.IGNORECASE)
    dest_match = re.search(r"to\s+(\w+)", user_input, re.IGNORECASE)
    activity_match = re.search(r"(sports|hiking|skiing|activities?)", user_input, re.IGNORECASE)

    origin = origin_match.group(1) if origin_match else "Unknown"
    destination = dest_match.group(1) if dest_match else "Unknown"
    activity = activity_match.group(1) if activity_match else "general"

    workflow = {
        "workflow": [
            {"api": "flight_api", "params": {"from": origin, "to": destination}},
            {"api": "hotel_api", "params": {"location": destination}},
            {"api": "weather_api", "params": {"location": destination}},
            {"api": "activity_api", "params": {"type": activity, "location": destination}}
        ]
    }
    return json.dumps(workflow)  # ✅ ensures valid JSON output


def extract_json(text: str) -> str:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError("No JSON found in model output")
    return match.group(0)
